/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEditor;
using UnityEngine;

namespace Fungus.EditorUtils
{
    [CustomPropertyDrawer(typeof(Collision2DData))]
    public class Collision2DDataDrawer : VariableDataDrawer<Collision2DVariable>
    { }
}