/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEditor;
using UnityEngine;

namespace Fungus.EditorUtils
{
    [CustomPropertyDrawer(typeof(NavMeshAgentData))]
    public class NavMeshAgentDataDrawer : VariableDataDrawer<NavMeshAgentVariable>
    { }
}