/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEngine;


namespace Fungus
{
    /// <summary>
    /// Collision2D variable type.
    /// </summary>
    [VariableInfo("Other", "Collision2D")]
    [AddComponentMenu("")]
	[System.Serializable]
	public class Collision2DVariable : VariableBase<UnityEngine.Collision2D>
	{ }

	/// <summary>
	/// Container for a Collision2D variable reference or constant value.
	/// </summary>
	[System.Serializable]
	public struct Collision2DData
	{
		[SerializeField]
		[VariableProperty("<Value>", typeof(Collision2DVariable))]
		public Collision2DVariable collision2DRef;

		[SerializeField]
		public UnityEngine.Collision2D collision2DVal;

		public static implicit operator UnityEngine.Collision2D(Collision2DData Collision2DData)
		{
			return Collision2DData.Value;
		}

		public Collision2DData(UnityEngine.Collision2D v)
		{
			collision2DVal = v;
			collision2DRef = null;
		}

		public UnityEngine.Collision2D Value
		{
			get { return (collision2DRef == null) ? collision2DVal : collision2DRef.Value; }
			set { if (collision2DRef == null) { collision2DVal = value; } else { collision2DRef.Value = value; } }
		}

		public string GetDescription()
		{
			if (collision2DRef == null)
			{
				return collision2DVal.ToString();
			}
			else
			{
				return collision2DRef.Key;
			}
		}
	}
}