/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEngine;


namespace Fungus
{
    /// <summary>
    /// NavMeshAgent variable type.
    /// </summary>
    [VariableInfo("Other", "NavMeshAgent")]
    [AddComponentMenu("")]
	[System.Serializable]
	public class NavMeshAgentVariable : VariableBase<UnityEngine.AI.NavMeshAgent>
	{ }

	/// <summary>
	/// Container for a NavMeshAgent variable reference or constant value.
	/// </summary>
	[System.Serializable]
	public struct NavMeshAgentData
	{
		[SerializeField]
		[VariableProperty("<Value>", typeof(NavMeshAgentVariable))]
		public NavMeshAgentVariable navMeshAgentRef;

		[SerializeField]
		public UnityEngine.AI.NavMeshAgent navMeshAgentVal;

		public static implicit operator UnityEngine.AI.NavMeshAgent(NavMeshAgentData NavMeshAgentData)
		{
			return NavMeshAgentData.Value;
		}

		public NavMeshAgentData(UnityEngine.AI.NavMeshAgent v)
		{
			navMeshAgentVal = v;
			navMeshAgentRef = null;
		}

		public UnityEngine.AI.NavMeshAgent Value
		{
			get { return (navMeshAgentRef == null) ? navMeshAgentVal : navMeshAgentRef.Value; }
			set { if (navMeshAgentRef == null) { navMeshAgentVal = value; } else { navMeshAgentRef.Value = value; } }
		}

		public string GetDescription()
		{
			if (navMeshAgentRef == null)
			{
				return navMeshAgentVal.ToString();
			}
			else
			{
				return navMeshAgentRef.Key;
			}
		}
	}
}