/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEngine;


namespace Fungus
{
    /// <summary>
    /// Quaternion variable type.
    /// </summary>
    [VariableInfo("Other", "Quaternion", HasCustomDraw = true)]
    [AddComponentMenu("")]
	[System.Serializable]
	public class QuaternionVariable : VariableBase<UnityEngine.Quaternion>
    {
#if UNITY_EDITOR
        public override void InternalDrawProperty(Rect rect, UnityEditor.SerializedProperty valueProp)
        {
            //show it as euler angles.
            valueProp.quaternionValue = Quaternion.Euler(UnityEditor.EditorGUI.Vector3Field(rect, new GUIContent(""), valueProp.quaternionValue.eulerAngles));
        }
#endif//UNITY_EDITOR
    }

        /// <summary>
        /// Container for a Quaternion variable reference or constant value.
        /// </summary>
        [System.Serializable]
	public struct QuaternionData
	{
		[SerializeField]
		[VariableProperty("<Value>", typeof(QuaternionVariable))]
		public QuaternionVariable quaternionRef;

		[SerializeField]
		public UnityEngine.Quaternion quaternionVal;

		public static implicit operator UnityEngine.Quaternion(QuaternionData QuaternionData)
		{
			return QuaternionData.Value;
		}

		public QuaternionData(UnityEngine.Quaternion v)
		{
			quaternionVal = v;
			quaternionRef = null;
		}

		public UnityEngine.Quaternion Value
		{
			get { return (quaternionRef == null) ? quaternionVal : quaternionRef.Value; }
			set { if (quaternionRef == null) { quaternionVal = value; } else { quaternionRef.Value = value; } }
		}

		public string GetDescription()
		{
			if (quaternionRef == null)
			{
				return quaternionVal.ToString();
			}
			else
			{
				return quaternionRef.Key;
			}
		}
    }
}