/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEngine;


namespace Fungus
{
    /// <summary>
    /// Rigidbody2D variable type.
    /// </summary>
    [VariableInfo("Other", "Rigidbody2D")]
    [AddComponentMenu("")]
	[System.Serializable]
	public class Rigidbody2DVariable : VariableBase<UnityEngine.Rigidbody2D>
	{ }

	/// <summary>
	/// Container for a Rigidbody2D variable reference or constant value.
	/// </summary>
	[System.Serializable]
	public struct Rigidbody2DData
	{
		[SerializeField]
		[VariableProperty("<Value>", typeof(Rigidbody2DVariable))]
		public Rigidbody2DVariable rigidbody2DRef;

		[SerializeField]
		public UnityEngine.Rigidbody2D rigidbody2DVal;

		public static implicit operator UnityEngine.Rigidbody2D(Rigidbody2DData Rigidbody2DData)
		{
			return Rigidbody2DData.Value;
		}

		public Rigidbody2DData(UnityEngine.Rigidbody2D v)
		{
			rigidbody2DVal = v;
			rigidbody2DRef = null;
		}

		public UnityEngine.Rigidbody2D Value
		{
			get { return (rigidbody2DRef == null) ? rigidbody2DVal : rigidbody2DRef.Value; }
			set { if (rigidbody2DRef == null) { rigidbody2DVal = value; } else { rigidbody2DRef.Value = value; } }
		}

		public string GetDescription()
		{
			if (rigidbody2DRef == null)
			{
				return rigidbody2DVal.ToString();
			}
			else
			{
				return rigidbody2DRef.Key;
			}
		}
	}
}