/*This script has been, partially or completely, generated by the Fungus.GenerateVariableWindow*/
using UnityEngine;


namespace Fungus
{
    // <summary>
    /// Get or Set a property of a Collision2D component
    /// </summary>
    [CommandInfo("Collision2D",
                 "Property",
                 "Get or Set a property of a Collision2D component")]
    [AddComponentMenu("")]
    public class Collision2DProperty : BaseVariableProperty
    {
		//generated property
        public enum Property 
        { 
            Rigidbody, 
            OtherRigidbody, 
            Transform, 
            GameObject, 
            RelativeVelocity, 
            Enabled, 
        }

		
        [SerializeField]
        protected Property property;
		
        [SerializeField]
        protected Collision2DData collision2DData;

        [SerializeField]
        [VariableProperty(typeof(Rigidbody2DVariable),
                          typeof(TransformVariable),
                          typeof(GameObjectVariable),
                          typeof(Vector2Variable),
                          typeof(BooleanVariable))]
        protected Variable inOutVar;

        public override void OnEnter()
        {
            var iorb2d = inOutVar as Rigidbody2DVariable;
            var iot = inOutVar as TransformVariable;
            var iogo = inOutVar as GameObjectVariable;
            var iov2 = inOutVar as Vector2Variable;
            var iob = inOutVar as BooleanVariable;


            var target = collision2DData.Value;

            switch (getOrSet)
            {
                case GetSet.Get:
                    switch (property)
                    {
                        case Property.Rigidbody:
                            iorb2d.Value = target.rigidbody;
                            break;
                        case Property.OtherRigidbody:
                            iorb2d.Value = target.otherRigidbody;
                            break;
                        case Property.Transform:
                            iot.Value = target.transform;
                            break;
                        case Property.GameObject:
                            iogo.Value = target.gameObject;
                            break;
                        case Property.RelativeVelocity:
                            iov2.Value = target.relativeVelocity;
                            break;
                        case Property.Enabled:
                            iob.Value = target.enabled;
                            break;
                        default:
                            Debug.Log("Unsupported get or set attempted");
                            break;
                    }

                    break;
                case GetSet.Set:
                    switch (property)
                    {
                        default:
                            Debug.Log("Unsupported get or set attempted");
                            break;
                    }

                    break;
                default:
                    break;
            }

            Continue();
        }

        public override string GetSummary()
        {
            if (collision2DData.Value == null)
            {
                return "Error: no collision2D set";
            }
            if (inOutVar == null)
            {
                return "Error: no variable set to push or pull data to or from";
            }

            return getOrSet.ToString() + " " + property.ToString();
        }

        public override Color GetButtonColor()
        {
            return new Color32(235, 191, 217, 255);
        }

        public override bool HasReference(Variable variable)
        {
            if (collision2DData.collision2DRef == variable || inOutVar == variable)
                return true;

            return false;
        }

    }
}